version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - echo checking the python version
      - python3 --version
      - echo
      - pip3 install cfn-lint
      - echo checking the cfn-lint version
      - cfn-lint --version

  build:
    commands:
      - echo testing our template
      - cfn-lint us-eastTemplate.yml
      - echo Build started on `date`
      - aws cloudformation package --template-file us-eastTemplate.yml --s3-bucket deploy-end-to-end-bucket --output-template-file artifactoutput.yml

  post_build:
    commands:
      - echo Build completed on `date`
      - ls -l
artifacts:
  files:
    - us-eastTemplate.yml
    - artifactoutput.yml