version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  pre_build:
    commands:
      - echo checking the python version
      - python3 --version
      - echo
      - pip3 installing cfn-lint
      - echo checking the cfn-lint version
      - cfn-lint --version

  build:
    commands:
      - echo testing our template
      - echo Build started on `date`
      - echo we are entering the build phase in the dev environment
  post_build:
    commands:
      - echo Build completed on `date`
      - ls -l
artifacts:
  files:
    - '**/*'